name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r src/pc_app/requirements.txt
          pip install pyinstaller

      - name: Show installed packages
        run: pip list
        
      - name: Run build script
        run: src/build_scripts/build.bat

      - name: Zip build
        run: |
          powershell Compress-Archive src/build_scripts/dist/OsciFootswitch OsciFootswitch.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: OsciFootswitch.zip
